name: macOS CI

# Workflow syntax.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PACKAGE_NAME: aws-lc
  # Used to enable ASAN test dimension.
  AWSLC_NO_ASM_FIPS: 1

jobs:
  macOS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }}
      run: |
        ./tests/ci/run_posix_tests.sh

  macOS-FIPS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }} with FIPS mode
      run: |
        ./tests/ci/run_fips_tests.sh

  macOS-ARM:
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }}
      run: |
        ./tests/ci/run_posix_tests.sh

  macOS-ARM-FIPS:
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }} with FIPS mode
      run: |
        ./tests/ci/run_fips_tests.sh

