name: Windows Tests
on:
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  GOPROXY: https://proxy.golang.org,direct
  SDE_MIRROR_URL: "https://downloadmirror.intel.com/777395/sde-external-9.21.1-2023-04-24-win.tar.xz"
  SDE_VERSION_TAG: sde-external-9.21.1-2023-04-24-win

jobs:
  MSVC-2019:
    runs-on: temporary-performance-testing_windows-2019_8-core
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Build Windows Dependencies
        run: |
          choco install ninja --version 1.9.0.20190208 -y &&
          choco install nasm --version 2.14.02 -y
      - name: Run Windows Tests on MSVC-2019
        run: |
          .\tests\ci\run_windows_tests.bat "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

  MSVC-2022:
    runs-on: temporary-performance-testing_windows-latest_8-core
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Build Windows Dependencies
        run: |
          choco install ninja --version 1.9.0.20190208 -y &&
          choco install nasm --version 2.14.02 -y
      - name: Run Windows Tests on MSVC-2022
        run: |
          .\tests\ci\run_windows_tests.bat "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

  SDE-64-bit:
    # TODO: Update this to run on windows-2022. We're running against windows-2019 for x64 for the time being.
    runs-on: temporary-performance-testing_windows-latest_64-core
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Build Windows Dependencies
        run: |
          choco install ninja --version 1.9.0.20190208 -y &&
          choco install nasm --version 2.14.02 -y

      - name: Install SDE simulator
        run: |
          curl -SL --output temp.tar.xz ${{ env.SDE_MIRROR_URL }}
          7z x temp.tar.xz
          7z x temp.tar
          ren ${{ env.SDE_VERSION_TAG }} windows-sde
          del temp.tar.xz
          del temp.tar

      - name: Run Windows SDE Tests for 64 bit
        run: |
          $env:SDEROOT = "${PWD}\windows-sde"
          echo ${env:SDEROOT}
          .\tests\ci\run_windows_tests.bat "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 true

  SDE-32-bit:
    runs-on: temporary-performance-testing_windows-2019_64-core
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Build Windows Dependencies
        run: |
          choco install ninja --version 1.9.0.20190208 -y &&
          choco install nasm --version 2.14.02 -y

      - name: Install SDE simulator
        run: |
          curl -SL --output temp.tar.xz ${{ env.SDE_MIRROR_URL }}
          7z x temp.tar.xz
          7z x temp.tar
          ren ${{ env.SDE_VERSION_TAG }} windows-sde
          del temp.tar.xz
          del temp.tar

      - name: Run Windows SDE Tests for 32 bit
        run: |
          $env:SDEROOT = "${PWD}\windows-sde"
          echo ${env:SDEROOT}
          .\tests\ci\run_windows_tests.bat "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 true

